###
GET http://localhost:4000/api/users HTTP/1.1


###
POST  http://localhost:4000/api/users HTTP/1.1
CONTENT-TYPE: application/json

{
    "name" : "Johna Doe",
    "password": "admin",
    "roleId": 1
}
